mysite_122/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    logout_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
)


app_name = "myauth"
urlpatterns = [
    # path("login/", login_view, name="login"),
    path("login/",
         LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
         ),
         name="login"),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite_122/mysite_122/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('app_pages/', include('app_pages.urls')),
    path('app_pagesi18n/', include('django.conf.urls.i18n')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),

    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap")
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite_122/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
)

routers = DefaultRouter()
routers.register("products", ProductViewSet)

app_name = "shopapp"
urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-archive/", ProductDeleteView.as_view(), name="product_delete"),
    # path("products/create/", create_product, name="product_create"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order_details"),
]

mysite_122/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


def product_previews_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        verbose_name_plural = _('products')
        verbose_name = _('product')
        ordering = ["name", "price"]

    name = models.CharField(max_length=100, verbose_name=_('name'), db_index=True)
    description = models.TextField(null=False, blank=True, verbose_name=_('description'), db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, verbose_name=_('price'))
    discount = models.SmallIntegerField(default=0, verbose_name=_('discount'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))
    archived = models.BooleanField(default=False, verbose_name=_('archived'))
    preview = models.ImageField(null=True, blank=True, upload_to=product_previews_directory_path, verbose_name=_('preview'))

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

mysite_122/shopapp/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm
from django import forms
from shopapp.models import Product


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]

mysite_122/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам, и тд
"""
from csv import DictWriter

import logging
from timeit import default_timer

from django.contrib.auth.models import Group
from django.http import \
    HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.core.cache import cache
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from .serializers import ProductSerializer
from .forms import GroupForm, ProductForm
from .models import Product, Order, ProductImage
from .common import save_csv_products

log = logging.getLogger(__name__)

@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = ["name", "description", "price", "discount", ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)        # field: получить атрибуты с объекта product по ключу field
                for field in fields
            })

        return response

    @action(
        detail=False,
        methods=["post"],
        parser_classes=[MultiPartParser],
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        # print("Hello Products List")
        return super().list(*args, **kwargs)


class ShopIndexView(View):
    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
        }

        # print("Shop Index context", context)

        # log.debug("Products for Shop Index: %s", products)
        # log.info("Rendering Shop Index")
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = "shopapp/product-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductsListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


# class ProductCreateView(UserPassesTestMixin, CreateView):
class ProductCreateView(CreateView):
    # def test_func(self):
    #     return self.request.user.is_superuser

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")


class ProductUpdateView(UpdateView):
    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

# def create_product(request: HttpRequest) -> HttpResponse:
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # name = form.cleaned_data["name"]
#             # price = form.cleaned_data["price"]
#             # Product.objects.create(**form.cleaned_data)
#             form.save()
#             url = reverse("shopapp:products_list")
#             return redirect(url)
#     else:
#         form = ProductForm()
#     context = {
#         "form": form,
#     }
#     return render(request, 'shopapp/create-product.html', context=context)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects.
        select_related("user")
        .prefetch_related("products")
    )


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)
        if products_data is None:
            products = Product.objects.order_by("pk").all()
            products_data = [
                {
                    "pk": product.pk,
                    "name": product.name,
                    "price": product.price,
                    "archived": product.archived,
                }
                for product in products
            ]
            elem = products_data[0]
            name = elem["name"]
            print("name:", name)
            cache.set(cache_key, products_data, 300)
        return JsonResponse({"products": products_data})

mysite_122/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>

{% block body %}
    Base Body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_wwekday %}
    Today is {{ current_wwekday }}
</div>

</body>
</html>

mysite_122/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">
                Create
            </button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
     <div>
     {% if not groups %}
        <h3>No groups yet</h3>
     {% else %}
         <ul>
            {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{ permission.name }}
                                (<code>{{ permission.codename }}</code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
         </ul>
     {% endif %}
     </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
        <p>Order by {% firstof object.user.first_name object.user.username %}</p>
        <p>Promocode: <code>{{ object.promocode }}</code></p>
        <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
        Product in order:
    </div>
    <ul>
        {% for product in order.products.all %}
            <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}

    </ul>
    </div>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
            <div>
                Product in order:
            </div>
            <ul>
                {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                {% endfor %}
                
            </ul>
            </div>
        {% endfor %}
        
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %} 
{% endblock %}

mysite_122/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ priduct.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        <h3>Images:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>No images uploaded yet</div>
            {% endfor %}
        </div>

    </div>
    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archive product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">archive</button>
        </form>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk%}">Back to product #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% load cache %}

{% block body %}
    <h1>Products:</h1>
    {% if products %}
        {% cache 500 footer %}
            <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                </div>
            {% endfor %}
            </div>
        {% endcache %}
    {% else %}
        <h3>No products yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:product_create' %}">Create a new product</a>
    </div>
{% endblock %}

mysite_122/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
{% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">Import CSV</a>
    </li>
    {{ block.super }}
{% endblock %}

mysite_122/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello, Shop Index!</h1>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
                {% if name|length_is:'7' %}
                    <span>Lucky Product</span>
                {% endif %}

                {% empty %}
                No products here
            {% endfor %}
            
        </ul>
    </div>

    <div>
        Time running: {{ time_running }}
    </div>

    {% cache 100 lorem products %}
    <div>
        {% lorem 3 p random %}
    </div>
    {% endcache %}

{% endblock %}